os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64

configuration:
  #- Debug
  - Release

matrix:
  fast_finish: true

services:
  - postgresql

build_script:
  - CD
  - cd ..
  - CD
  - git clone https://github.com/HowardHinnant/date
  - cd date
  - git checkout tags/v2.4
  - cd ..
  - git clone https://github.com/rbock/sqlpp11
  - cd sqlpp11-connector-postgresql
  - CD
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_PREFIX_PATH="C:\projects\date" -DDATE_INCLUDE_DIR="C:\projects\date\include" -DSQLPP11_INCLUDE_DIR="C:\projects\sqlpp11\include"
  - cmake --build . --config %configuration%
  - ctest . --build-config %configuration%
