language: cpp

sudo: required
dist: xenial

compiler:
  - gcc
  #- clang

notifications:
  email:
    on_success: change
    on_failure: always

services:
  - postgresql

before_install:
  - pip install --user cpp-coveralls

install:
  - sudo apt-get install -y postgresql-server-dev-all libboost-dev
  - pwd
  - g++ --version
  - cmake --version
  - cd ..
  - git clone https://github.com/HowardHinnant/date
  - cd date
  - git checkout tags/v2.4
  - cmake -DCMAKE_BUILD_TYPE=Release -DTZ_CXX_STANDARD=11 .
  - make VERBOSE=1 && sudo make install
  - cd ..
  - git clone https://github.com/rbock/sqlpp11.git
  - cd sqlpp11
  - cmake -DCMAKE_BUILD_TYPE=Release .
  - make && sudo make install
  - cd ../sqlpp11-connector-postgresql

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -DCMAKE_MODULE_PATH="/usr/local/lib/cmake/Sqlpp11"

script:
  - cmake --build .
  - ctest --output-on-failure

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
