language: cpp

os:
  - linux
  - osx

osx_image: xcode7

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  - CONFIG=Debug

sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libboost-dev
    - libpq-dev
    - postgresql-server-dev-all

services:
  - postgresql

notifications:
  email:
    on_success: change
    on_failure: always

install:
  # install a newer cmake since at this time Travis only has version 2.8
  - pwd
  - PROJECT_DIR=$PWD
  - CMAKE_VERSION_MM=3.4
  - CMAKE_VERSION_FULL=$CMAKE_VERSION_MM.1
  - cd ..
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget --no-check-certificate http://www.cmake.org/files/v${CMAKE_VERSION_MM}/cmake-${CMAKE_VERSION_FULL}-Linux-x86_64.sh
      && sudo sh cmake-${CMAKE_VERSION_FULL}-Linux-x86_64.sh --prefix=/usr/local --exclude-subdir;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      && ((brew list -1 | grep -q "^$cmake\$") || brew install cmake)
      && (brew outdated cmake || brew upgrade cmake)
      && cmake --version
      ;
    fi
  - git clone --branch v1.0.0 --depth 1 https://github.com/HowardHinnant/date
  - git clone --branch develop --depth 1 https://github.com/rbock/sqlpp11.git
  - cd sqlpp11
  - mkdir build
  - cd build
  - cmake .. -DHinnantDate_ROOT_DIR="$PROJECT_DIR/../date" -DCMAKE_BUILD_TYPE=$CONFIG
  - sudo make install
  - cd ../..
  - psql -c 'CREATE DATABASE sqlpp11_tests;' postgres
  - cd $PROJECT_DIR

before_script:
  - mkdir build
  - cd build
  - cmake .. -DHinnantDate_ROOT_DIR="$PWD/../../date" -DCMAKE_BUILD_TYPE=$CONFIG

script:
  - make VERBOSE=1
  - cmake --build . --config=$CONFIG
  - ctest --output-on-failure
